spring.application.name=Patient Service


#UNCOMMENT TO USE INMEMORY DATABASE
#spring.h2.console.path=/h2-console
#spring.datasource.url=jdbc:h2:mem:testdb
#spring.datasource.driver-class-name=org.h2.Driver
#spring.datasource.username=admin_viewer
#spring.datasource.password=password
#
#spring.jpa.database-platform=org.hibernate.dialect.H2Dialect
#
## If any changes in entity then update the schema
#spring.jpa.hibernate.ddl-auto=update
#spring.sql.init.mode=always

server.port=4000
#we saying all our error info log to terminal
logging.level.root=info
