### create a new patient
POST http://localhost:4000/patients
Content-Type: application/json

{
  "name" : "Hemant Kumar with billing Account",
  "email": "hemant.kumar@example.com",
  "address" : "India",
  "dateOfBirth": "1999-07-19",
  "registeredDate": "2025-06-08"
}

###