### update a existing patient
PUT http://localhost:4000/patients/123e4567-e89b-12d3-a456-426614174000
Content-Type: application/json

{
  "name" : "Name UPDATED again",
  "email" : "john.doe@example.com",
  "address" : "D103 third floor ",
  "dateOfBirth": "1999-07-26"
}

###